# src/config/model_setup/mlp.yaml

training:
  monitor_metric: f1_macro
  batch_size: 512
  epochs: 500
  patience: 50
  lr: 0.001
  weight_decay:  0.001
  device: cuda

model:
  hidden_dims:
    - 512
    - 256
    - 128
    - 64
    - 32